version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: youtube
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aman06
    ports:
      - "5436:5432"

  jwt_yt_app:
    image: jwt-yt-app
    container_name: jwt_yt_app_container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/youtube
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: aman06
